name: backend

on:
  push:
    paths:
    - ".github/workflows/backend.yml"
    - "CMakeLists.txt"
    - "src/*"
    - "scripts/*"
  pull_request:
    paths:
    - ".github/workflows/backend.yml"
    - "CMakeLists.txt"
    - "src/*"
    - "scripts/*"
  workflow_call:

jobs:
  cross:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v4
      - name: use freebsd-vm action
        uses: vmactions/freebsd-vm@v1
        env:
          BUILD_TARGET: ${{ matrix.target }}
        with:
          usesh: true
          sync: sshfs
          envs: 'BUILD_TARGET'
          prepare: |
            pkg install -y autoconf automake cmake curl file libtool git libwebsockets
          run: |
            echo $GITHUB_WORKSPACE
            echo $PATH
            export PATH=$PATH;$GITHUB_WORKSPACE/scripts
            pwd ls -la
            cross-build.sh
            pwd
            ls -la
            ls -la build
      - uses: actions/upload-artifact@v4
        with:
          name: ttyd.${{ matrix.target }}
          path: build/ttyd*

